package dev.sim0n.anticheat.util;

import lombok.experimental.UtilityClass;
import org.bukkit.ChatColor;

@UtilityClass
public class CC {
    public final String BLUE = ChatColor.BLUE.toString();
    public final String AQUA = ChatColor.AQUA.toString();
    public final String YELLOW = ChatColor.YELLOW.toString();
    public final String RED = ChatColor.RED.toString();
    public final String GRAY = ChatColor.GRAY.toString();
    public final String GOLD = ChatColor.GOLD.toString();
    public final String GREEN = ChatColor.GREEN.toString();
    public final String WHITE = ChatColor.WHITE.toString();
    public final String BLACK = ChatColor.BLACK.toString();
    public final String BOLD = ChatColor.BOLD.toString();
    public final String ITALIC = ChatColor.ITALIC.toString();
    public final String STRIKE_THROUGH = ChatColor.STRIKETHROUGH.toString();
    public final String RESET = ChatColor.RESET.toString();
    public final String MAGIC = ChatColor.MAGIC.toString();
    public final String OBFUSCATED = MAGIC;
    public final String B = BOLD;
    public final String M = MAGIC;
    public final String O = MAGIC;
    public final String I = ITALIC;
    public final String S = STRIKE_THROUGH;
    public final String R = RESET;
    public final String DARK_BLUE = ChatColor.DARK_BLUE.toString();
    public final String DARK_AQUA = ChatColor.DARK_AQUA.toString();
    public final String DARK_GRAY = ChatColor.DARK_GRAY.toString();
    public final String DARK_GREEN = ChatColor.DARK_GREEN.toString();
    public final String DARK_PURPLE = ChatColor.DARK_PURPLE.toString();
    public final String DARK_RED = ChatColor.DARK_RED.toString();
    public final String D_BLUE = DARK_BLUE;
    public final String D_AQUA = DARK_AQUA;
    public final String D_GRAY = DARK_GRAY;
    public final String D_GREEN = DARK_GREEN;
    public final String D_PURPLE = DARK_PURPLE;
    public final String D_RED = DARK_RED;
    public final String LIGHT_PURPLE = ChatColor.LIGHT_PURPLE.toString();
    public final String L_PURPLE = LIGHT_PURPLE;
    public final String PINK = L_PURPLE;
    public final String B_BLUE = BLUE + B;
    public final String B_AQUA = AQUA + B;
    public final String B_YELLOW = YELLOW + B;
    public final String B_RED = RED + B;
    public final String B_GRAY = GRAY + B;
    public final String B_GOLD = GOLD + B;
    public final String B_GREEN = GREEN + B;
    public final String B_WHITE = WHITE + B;
    public final String B_BLACK = BLACK + B;
    public final String BD_BLUE = D_BLUE + B;
    public final String BD_AQUA = D_AQUA + B;
    public final String BD_GRAY = D_GRAY + B;
    public final String BD_GREEN = D_GREEN + B;
    public final String BD_PURPLE = D_PURPLE + B;
    public final String BD_RED = D_RED + B;
    public final String BL_PURPLE = L_PURPLE + B;
    public final String I_BLUE = BLUE + I;
    public final String I_AQUA = AQUA + I;
    public final String I_YELLOW = YELLOW + I;
    public final String I_RED = RED + I;
    public final String I_GRAY = GRAY + I;
    public final String I_GOLD = GOLD + I;
    public final String I_GREEN = GREEN + I;
    public final String I_WHITE = WHITE + I;
    public final String I_BLACK = BLACK + I;
    public final String ID_RED = D_RED + I;
    public final String ID_BLUE = D_BLUE + I;
    public final String ID_AQUA = D_AQUA + I;
    public final String ID_GRAY = D_GRAY + I;
    public final String ID_GREEN = D_GREEN + I;
    public final String ID_PURPLE = D_PURPLE + I;
    public final String IL_PURPLE = L_PURPLE + I;
    public final String BLANK_LINE = "§8 §8 §1 §3 §3 §7 §8 §r";
}
